### ISSUE TITLE
Investigate Ambilight

### ISSUE THREAD

**Issue by ProjectSynchro** [ProjectSynchro/com.artemis_rgb.Artemis#3]
Currently Ambilight locks up the initial first load of Artemis for some reason, despite having the correct dri permissions to access the GPU.

This is worked around for now by not building the Plugin.

**Comment by micartey** [comment]
How did you "worked around" it?

**Comment by ProjectSynchro** [comment]
This seems to have gone away with the switch to upstream binary releases.
